---

- hosts: all
  become: true
  tasks:
          - name: Update Repository index
            apt:
                    update_cache: yes
                    upgrade: dist
                    autoremove: yes
                    autoclean: yes

