---

- hosts: all
  tasks:
          - name: update Repository index
            apt:
                    update_cache: yes

          - name: install apache2 package
            apt:
                    name: apache2
                    state: latest
           
          - name: Add php Support for apache2
            apt:
                    name: libapache2-mod-php
                    state: latest         
