---

- hosts: all
  tasks:
          - name: update Repository index
            apt:
                    update_cache: yes

          - name: Remove apache2, PHP and MariaDB package
            package:
                    name: 
                      - apache2
                      - libapache2-mod-php
                      - mariadb-server
                      - nginx
                      - nginx-core
                      - nginx-common
                    state: absent
#
#          - name: Remove MariaDB Package
#            apt:
#                    name: mariadb-server
#                    state: absent         
