---

- hosts: all
  pre_tasks:
          - name: Update Repository index
            apt:
                    upgrade: dist
                    update_cache: yes

- hosts: web_servers
  tasks:
          - name: Install Apache2, PHP package at Webserver.
            package:
                    name:
                            - apache2
                            - libapache2-mod-php
                    state: latest
            when: ansible_distribution == "Ubuntu"

          - name: copy html file for site
            copy:
                    src: hello.html
                    dest: /var/www/html/index.html
                    owner: root
                    group: root
                    mode: 0644


- hosts: db_servers
  tasks:

          - name: MariaDB package Installation at Database Server.
            apt:
                    name: mariadb-server
                    state: latest
           
- hosts: local
  tasks:

          - name: Nginx package Installation at localhost Server.
            apt:
                    name: nginx
                    state: latest
#           - name: Add php Support for apache2
#            apt:
#                    name: libapache2-mod-php
#                    state: latest         
