---

- hosts: all
  pre_tasks:
          - name: Update Repository index
            apt:
                    upgrade: dist
                    update_cache: yes

- hosts: web_servers
  tasks:
          - name: Install Apache2, PHP package at Webserver.
            package:
                    name:
                            - apache2
                            - libapache2-mod-php
                    state: latest
            when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  tasks:

          - name: MariaDB package Installation at Database Server.
            apt:
                    name: mariadb-server
                    state: latest
           
#           - name: Add php Support for apache2
#            apt:
#                    name: libapache2-mod-php
#                    state: latest         
